program: place_cell_rnn_sweep.py
project: rnn_sweep_bptt_trunc
name: search_v1
method: bayes

metric:
  goal: minimize
  name: loss

parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 0.00005
    max: 0.05
  decay_rate:
    values: [0.6, 0.7, 0.8, 0.9, 1.0]
  weight_decay:
    values: [0, 0.00001, 0.0001, 0.001]
  truncating:
    distribution: int_uniform
    min: 0
    max: 9

early_terminate:
  type: hyperband
  min_iter: 10

command:
- python
- ${program}
- --sequence_length
- "10"
- --batch_size
- "1"
- --n_steps 
- "1000"
- --n_epochs
- "100"
- --decay_step_size
- "10"
- --save
- "False"
- --out_activation
- "softmax"
- --rec_activation
- "relu"
- --loss
- "CE"
- --is_wandb
- "True"
- --sweep
- "True"
- --update_weights_online 
- "False"
- --use_prev_input 
- "False"

